apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: flux-sample
spec:
  size: 4
  interactive: true

  flux:
    container:
      image: ghcr.io/converged-computing/flux-view-rocky:arm-9

  # Note that I have not tested these containers!
  containers:

    # This is the main application container with lammps on rocky (no Flux)
    - image: ghcr.io/rse-ops/arm-lammps:rocky-9
      runFlux: true

    # This is a vanilla sidecar we install the metrics operator to.
    # What I'm not sure about here is if the arm platform will be selected (I hope so)
    - image: rockylinux:9
      name: metrics
      commands:
        post: |
          if [[ ${JOB_COMPLETION_INDEX} -eq 0 ]]; then
            dnf install -y git
            # Finalize the view so we can use Python (not default for a sidecar)
            cp -R /mnt/flux/software /opt/software
            git clone https://github.com/converged-computing/flux-metrics-api /opt/metrics-api
            cd /opt/metrics-api
            source /mnt/flux/flux-view.sh
            /mnt/flux/view/bin/python3.11 -m ensurepip
            /mnt/flux/view/bin/python3.11 -m pip install .
            export FLUX_URI=$fluxsocket
            unset LD_LIBRARY_PATH PYTHONPATH
            flux-metrics-api start --port 5000 --namespace default --host 0.0.0.0
          else
             sleep infinity
          fi