apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: scaling-study-efa-hossen1-10102023-16
  region: us-east-1
  version: "1.27"

availabilityZones: ["us-east-1a", "us-east-1b"]
managedNodeGroups:
  - name: scaling-study-efa-hossen1-10112023-16
    availabilityZones: ["us-east-1a"]
    instanceType: hpc7g.16xlarge
    minSize: 16
    maxSize: 16
    desiredCapacity: 16
    efaEnabled: true
    placement:
      groupName: eks-efa-testing
    labels: { "flux-operator": "true" }
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_rsa.pub