apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: flux-sample
  namespace: flux-operator
spec:
  size: 1
  maxSize: 8
  interactive: true

  flux:
    arch: "arm"
    completeWorkers: true
    container:
      image: ghcr.io/converged-computing/flux-view-ubuntu:arm-jammy

  containers:
    - image: ghcr.io/rajibhossen/amg2023:arm64
      runFlux: true
      commands:
        pre: |
          sleep infinity
    - image: ubuntu:jammy
      name: metrics
      commands:
        post: |
          if [[ ${JOB_COMPLETION_INDEX} -eq 0 ]]; then
            echo "We are in the loop"
            apt-get update && apt-get install -y git
            # Finalize the view so we can use Python (not default for a sidecar)
            cp -R /mnt/flux/software /opt/software
            git clone https://github.com/converged-computing/flux-metrics-api /opt/metrics-api
            cd /opt/metrics-api
            source /mnt/flux/flux-view.sh
            /mnt/flux/view/bin/python3.11 -m ensurepip
            /mnt/flux/view/bin/python3.11 -m pip install .
            export FLUX_URI=$fluxsocket
            unset LD_LIBRARY_PATH PYTHONPATH
            flux-metrics-api start --port 5000 --namespace default --host 0.0.0.0
          else
             echo "Looping infinitely"
             sleep infinity
          fi