apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: scaling-study-efa-hossen1-09212023-temp
  region: us-east-1
  version: "1.27"

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: cluster-autoscaler
      namespace: kube-system
    attachPolicy:
      Version: "2012-10-17"
      Statement:
      - Effect: Allow
        Action:
        - "autoscaling:DescribeAutoScalingGroups"
        - "autoscaling:DescribeAutoScalingInstances"
        - "autoscaling:DescribeLaunchConfigurations"
        - "autoscaling:DescribeTags"
        - "autoscaling:SetDesiredCapacity"
        - "autoscaling:TerminateInstanceInAutoScalingGroup"
        - "ec2:DescribeLaunchTemplateVersions"
        - "eks:DescribeNodegroup"
        Resource: '*'

availabilityZones: ["us-east-1a", "us-east-1b"]
managedNodeGroups:
  - name: scaling-study-efa-hossen1-09212023-temp
    availabilityZones: ["us-east-1a"]
    instanceType: c5n.9xlarge
    minSize: 2
    maxSize: 2
    desiredCapacity: 2
    efaEnabled: true
    placement:
      groupName: eks-efa-testing
    labels: { "flux-operator": "true" }
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/scaling-study-efa: "owned"
      Name: 'scaling-study-efa-hossen1-09212023-temp'
    propagateASGTags: true
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_rsa.pub

  - name: scaling-study-efa-hossen1-09212023-temp-spot
    spot: true
    availabilityZones: [ "us-east-1a" ]
    instanceType: c5n.9xlarge
    minSize: 0
    maxSize: 50
    desiredCapacity: 0
    efaEnabled: true
    placement:
      groupName: eks-efa-testing
    labels: { "flux-operator": "true" }
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/scaling-study-efa: "owned"
      Name: 'scaling-study-efa-hossen1-09212023-temp'
    propagateASGTags: true
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_rsa.pub